### ISSUE TITLE
code = 500 reason =  message = auth failed

### ISSUE THREAD

**Issue by yimeng** [GuanceCloud/terraform-provider-guance#2]
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/1982337/233819774-88f3f64e-4e6a-4bc6-a377-aa7096861b93.png">

<img width="355" alt="image" src="https://user-images.githubusercontent.com/1982337/233819826-541f6abd-1480-4e9f-a3a8-dfc0b4cddff7.png">

<img width="135" alt="image" src="https://user-images.githubusercontent.com/1982337/233819841-efa805d8-8966-4668-a145-bbe8f364a064.png">

**Comment by yufeiminds** [comment]
Use Key ID as `GUANCE_TOKEN`. We will improve the documentation. 🌹
